export const REGISTER = 'users/auth/register';
export const LOGIN = 'users/auth/login';
export const VERIFY = 'users/auth/verify';
export const NEW_CODE = 'users/auth/new-code';
export const PROFILE = 'users/auth/profile';
export const APARTMENTS = 'services/apartments';
export const APARTMENTS_APPLICATIONS = 'services/apartments/applications';
export const BANNERS = 'services/banners';
export const CARS = 'services/cars';
export const ATRACTIONS = 'services/attractions';
export const ATRACTIONSSIMILAR = 'services/attractions/similar';
export const CARS_BRANDS = 'services/cars/brands';
export const CONCIERGES = 'services/concierges';
export const CONCIERGES_APPLICATIONS = 'services/concierges/applications';
export const MICE_SERVICES = 'services/mice-services';
export const MICE_SERVICES_APPLICATIONS = 'services/mice-services/applications';
export const SHOPPING_GOLDS = 'services/shopping/golds';
export const SHOPPING_GOLDS_APPLICATIONS =
  'services/shopping/golds/applications';
export const AIRPORTS = 'services/airporsts';
export const TRANSFERS = 'services/transfers';
export const POPULAR_QUESTIONS = 'home/popular-questions';
export const BASKET = 'payment/basket';
export const BASKETCREATE = `${BASKET}/create`;
export const BASKETDELETE = `${BASKET}/delete`;
export const TRANSFERORDER = `payment/order/transfer`
