type Product = {
  id?: string | number;
  name?: string;
  price?: number | string;
  bedrooms?: string;
  address?: string;
  tag?: string;
  image?: string;
  url?: string;
  km_per_day?: number;
  transmission?: string;
  year?: number;
  gear?: string;
  comment_count?: string;
  horsepower?: number;
  rating?: number;
  area?: number;
  bathrooms?: number;
  discount?: number | string;
  slug?: string;
  distance?: number;
  best_seller?: boolean;
  suffix?: any;
  sale?: boolean;
  created_at?: string;
  updated_at?: string;
  type?: string;
  passengers?: number;
  luggage?: number;
  poster?: string;
  other?: string
};
